# Generated by Django 5.1 on 2024-08-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_organization_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('ranking', models.IntegerField()),
                ('article_title', models.CharField(max_length=255)),
                ('reporter_name', models.CharField(max_length=255)),
                ('article_section', models.CharField(max_length=50)),
                ('monthly_article_count', models.IntegerField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
